apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-nginx-conf
  namespace: lab4

data:
  default.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      location = /api/arch {

        if ($http_authorization = "") {
          return 401;
        }

        default_type application/json;
        add_header Cache-Control "no-store";

        return 200 '{"arch":"nanoservices-kubernetes","component":"nginx-configmap"}';
      }

      location = /api/ping {
        default_type application/json;
        add_header Cache-Control "no-store";

        return 200 '{"ok":true}';
      }

      location = /api/checkout {
        proxy_pass http://checkout-svc/checkout;
      }
    }
